# -*- coding: utf-8 -*-
from pathlib import Path
replacements = {
    'frontend/assets/js/main.js': [
        ("showToast('Đã xóa khỏi yêu thích', 'info');", "showToast('Removed from favorites', 'info');"),
        ("showToast('Đã thêm vào yêu thích', 'success');", "showToast('Added to favorites', 'success');"),
        ("showToast('Đã xảy ra lỗi', 'error');", "showToast('An error occurred', 'error');"),
        ("modal.querySelector('.qv-description').textContent = book.description || 'Không có mô tả';",
         "modal.querySelector('.qv-description').textContent = book.description || 'No description available';"),
        ("return new Intl.NumberFormat('vi-VN').format(amount) + 'đ';",
         "return new Intl.NumberFormat('en-US').format(amount) + 'đ';")
    ],
    'frontend/functions/helpers.php': [
        ("return number_format($amount, 0, ',', '.') . 'đ';", "return number_format($amount, 0, ',', '.') . 'đ';"),
        ("'pending' => 'Chờ xác nhận',", "'pending' => 'Pending confirmation',"),
        ("'active' => 'Đang thuê',", "'active' => 'Active',"),
        ("'returned' => 'Đã trả',", "'returned' => 'Returned',"),
        ("'overdue' => 'Quá hạn',", "'overdue' => 'Overdue',"),
        ("'cancelled' => 'Đã hủy'", "'cancelled' => 'Cancelled'"),
        ("return 'Vừa xong';", "return 'Just now';"),
        ("return $mins . ' phút trước';", "return $mins . ' minutes ago';"),
        ("return $hours . ' giờ trước';", "return $hours . ' hours ago';"),
        ("return $days . ' ngày trước';", "return $days . ' days ago';")
    ],
    'frontend/templates/header.php': [
        ("<i class=\"fas fa-bell\"></i> Thông Báo", "<i class=\"fas fa-bell\"></i> Notifications"),
        ("<i class=\"fas fa-bell\"></i> Thông Báo", "<i class=\"fas fa-bell\"></i> Notifications"),
        ("<i class=\"fas fa-bell\"></i> Thông Báo", "<i class=\"fas fa-bell\"></i> Notifications"),
        ("<i class=\"fas fa-th-large\"></i> Dashboard", "<i class=\"fas fa-th-large\"></i> Dashboard"),
        ("<i class=\"fas fa-book\"></i> Rented Books", "<i class=\"fas fa-book\"></i> Rented Books"),
        ("<i class=\"fas fa-sign-out-alt\"></i> Logout", "<i class=\"fas fa-sign-out-alt\"></i> Logout")
    ],
    'frontend/templates/footer.php': [
        ("<h2 class=\"footer-cta-title\">Đăng ký nhận tin</h2>", "<h2 class=\"footer-cta-title\">Subscribe for Updates</h2>"),
        ("<p class=\"section-subtitle\">Nhận thông báo về sách mới và ưu đãi đặc biệt.</p>",
         "<p class=\"section-subtitle\">Get notified about new books and special offers.</p>"),
        ("placeholder=\"Nhập email của bạn\"", "placeholder=\"Enter your email\""),
        ("<p>Nền tảng thuê sách trực tuyến hàng đầu Việt Nam. Tiếp cận hàng ngàn đầu sách với chi phí hợp lý.</p>",
         "<p>The leading online book rental platform in Vietnam. Discover thousands of titles with affordable pricing.</p>"),
        ("<a href=\"index.php\"><i class=\"fas fa-chevron-right\"></i> Trang Chủ</a>", "<a href=\"index.php\"><i class=\"fas fa-chevron-right\"></i> Home</a>"),
        ("<a href=\"books.php\"><i class=\"fas fa-chevron-right\"></i> Sách</a>", "<a href=\"books.php\"><i class=\"fas fa-chevron-right\"></i> Books</a>"),
        ("<a href=\"about.php\"><i class=\"fas fa-chevron-right\"></i> Về Chúng Tôi</a>",
         "<a href=\"about.php\"><i class=\"fas fa-chevron-right\"></i> About Us</a>"),
        ("<a href=\"contact.php\"><i class=\"fas fa-chevron-right\"></i> Liên Hệ</a>",
         "<a href=\"contact.php\"><i class=\"fas fa-chevron-right\"></i> Contact</a>"),
        ("<h4>Hỗ Trợ</h4>", "<h4>Support</h4>"),
        ("<a href=\"faq.php\"><i class=\"fas fa-chevron-right\"></i> Câu Hỏi Thường Gặp</a>",
         "<a href=\"faq.php\"><i class=\"fas fa-chevron-right\"></i> FAQ</a>"),
        ("<a href=\"contact.php\"><i class=\"fas fa-chevron-right\"></i> Liên Hệ Hỗ Trợ</a>",
         "<a href=\"contact.php\"><i class=\"fas fa-chevron-right\"></i> Support Contact</a>"),
        ("<a href=\"#\"><i class=\"fas fa-chevron-right\"></i> Chính Sách Đổi Trả</a>",
         "<a href=\"#\"><i class=\"fas fa-chevron-right\"></i> Return Policy</a>"),
        ("<a href=\"#\"><i class=\"fas fa-chevron-right\"></i> Điều Khoản Sử Dụng</a>",
         "<a href=\"#\"><i class=\"fas fa-chevron-right\"></i> Terms of Service</a>"),
        ("<h4>Liên Hệ</h4>", "<h4>Contact</h4>"),
        ("<p><i class=\"fas fa-map-marker-alt\"></i> 123 Đường ABC, Quận 1, TP.HCM</p>",
         "<p><i class=\"fas fa-map-marker-alt\"></i> 123 ABC Street, District 1, Ho Chi Minh City</p>"),
        ("<p><i class=\"fas fa-clock\"></i> Thứ 2 - Thứ 6: 8:00 - 18:00</p>",
         "<p><i class=\"fas fa-clock\"></i> Mon - Fri: 8:00 - 18:00</p>"),
        ("<p>&copy; <?php echo date('Y'); ?> MÂY MƠ BOOK. Tất cả quyền được bảo lưu. | Made with <i class=\"fas fa-heart\" style=\"color: var(--danger);\"></i> in Vietnam</p>",
         "<p>&copy; <?php echo date('Y'); ?> MÂY MƠ BOOK. All rights reserved. | Made with <i class=\"fas fa-heart\" style=\"color: var(--danger);\"></i> in Vietnam</p>")
    ],
    'frontend/templates/admin_header.php': [
        ("<span class=\"sidebar-nav-label\">Quản lý chính</span>", "<span class=\"sidebar-nav-label\">Main Management</span>"),
        ("<span>Quản lý sách</span>", "<span>Book Management</span>"),
        ("<span>Quản lý thuê sách</span>", "<span>Rental Management</span>"),
        ("<span>Quản lý khách</span>", "<span>Customer Management</span>"),
        ("<span>Tin nhắn</span>", "<span>Messages</span>"),
        ("<span class=\"sidebar-nav-label\">Cài đặt</span>", "<span class=\"sidebar-nav-label\">Settings</span>"),
        ("<span>Cài đặt</span>", "<span>Settings</span>"),
        ("onclick=\"return confirm('Bạn có chắc chắn muốn đăng xuất?')\"", "onclick=\"return confirm('Are you sure you want to log out?')\""),
        ("<div class=\"sidebar-admin-role\">Quản trị viên</div>", "<div class=\"sidebar-admin-role\">Administrator</div>"),
        ("<span>Thông Báo</span>", "<span>Notifications</span>"),
        ("Đánh dấu tất cả đã đọc", "Mark all as read"),
        ("Có <?php echo $overdueCount; ?> đơn thuê bị quá hạn", "You have <?php echo $overdueCount; ?> overdue rentals"),
        ("<div class=\"notif-time\">Cần xử lý ngay</div>", "<div class=\"notif-time\">Requires attention</div>"),
        ("<div class=\"notif-time\">Chưa đọc</div>", "<div class=\"notif-time\">Unread</div>"),
        ("<span>Không có thông báo mới</span>", "<span>No new notifications</span>"),
        ("<a href=\"rentals.php?status=overdue\">Xem đơn quá hạn</a>", "<a href=\"rentals.php?status=overdue\">View overdue rentals</a>"),
        ("<span>Tin Nhắn</span>", "<span>Messages</span>"),
        ("<a href=\"messages.php\">Xem tất cả</a>", "<a href=\"messages.php\">View all</a>"),
        ("echo 'Hệ thống'", "echo 'System'"),
        ("echo htmlspecialchars($msg['sender_name'] ?? 'Không xác định')", "echo htmlspecialchars($msg['sender_name'] ?? 'Unknown')"),
        ("<span>Không có tin nhắn nào</span>", "<span>No messages yet</span>"),
        ("<a href=\"messages.php\">Đến hộp thư</a>", "<a href=\"messages.php\">Go to inbox</a>")
    ],
    'frontend/pages/contact.php': [
        ("$pageTitle = 'Liên Hệ';", "$pageTitle = 'Contact';"),
        ("<h1 style=\"font-size: 2rem; margin-bottom: 4px;\">Liên Hệ</h1>", "<h1 style=\"font-size: 2rem; margin-bottom: 4px;\">Contact</h1>"),
        ("<p style=\"margin: 0; color: var(--text-muted);\">Chúng tôi luôn sẵn sàng lắng nghe bạn</p>",
         "<p style=\"margin: 0; color: var(--text-muted);\">We are ready to hear from you</p>"),
        ("<strong>Cảm ơn bạn đã liên hệ!</strong>", "<strong>Thank you for contacting us!</strong>"),
        ("<p style=\"margin: 8px 0 0;\">Chúng tôi sẽ phản hồi trong vòng 24 giờ.</p>",
         "<p style=\"margin: 8px 0 0;\">We will respond within 24 hours.</p>"),
        ("<h2>Gửi Tin Nhắn</h2>", "<h2>Send a Message</h2>"),
        ("<p style=\"color: var(--text-muted); margin-bottom: 24px;\">Điền thông tin bên dưới và chúng tôi sẽ liên hệ lại với bạn sớm nhất có thể.</p>",
         "<p style=\"color: var(--text-muted); margin-bottom: 24px;\">Fill in your details and we will get back to you shortly.</p>"),
        ("<label>Họ và Tên *</label>", "<label>Full Name *</label>"),
        ("placeholder=\"Nhập họ và tên của bạn\"", "placeholder=\"Enter your full name\""),
        ("<label>Chủ đề *</label>", "<label>Subject *</label>"),
        ("<option value=\"\">Chọn chủ đề</option>", "<option value=\"\">Select a subject</option>"),
        ("<option value=\"order\">Hỗ trợ đơn hàng</option>", "<option value=\"order\">Order support</option>"),
        ("<option value=\"return\">Đổi trả sách</option>", "<option value=\"return\">Book return</option>"),
        ("<option value=\"membership\">Gói hội viên</option>", "<option value=\"membership\">Membership plan</option>"),
        ("<option value=\"partnership\">Hợp tác kinh doanh</option>", "<option value=\"partnership\">Business partnership</option>"),
        ("<option value=\"feedback\">Góp ý dịch vụ</option>", "<option value=\"feedback\">Service feedback</option>"),
        ("<option value=\"other\">Khác</option>", "<option value=\"other\">Other</option>"),
        ("<label>Nội dung *</label>", "<label>Message *</label>"),
        ("placeholder=\"Mô tả chi tiết vấn đề của bạn...\"", "placeholder=\"Describe your issue in detail...\""),
        ("<button type=\"submit\" class=\"btn btn-primary btn-lg\">\n                        <i class=\"fas fa-paper-plane\"></i> Gửi Tin Nhắn\n                    </button>",
         "<button type=\"submit\" class=\"btn btn-primary btn-lg\">\n                        <i class=\"fas fa-paper-plane\"></i> Send Message\n                    </button>"),
        ("<h2>Thông Tin Liên Hệ</h2>", "<h2>Contact Information</h2>"),
        ("<p style=\"color: var(--text-muted); margin-bottom: 32px;\">Bạn cũng có thể liên hệ trực tiếp với chúng tôi qua các kênh sau:</p>",
         "<p style=\"color: var(--text-muted); margin-bottom: 32px;\">You can also reach us directly through the channels below:</p>"),
        ("<h4>Địa Chỉ</h4>", "<h4>Address</h4>"),
        ("<p>123 Đường ABC, Quận 1<br>TP. Hồ Chí Minh, Việt Nam</p>",
         "<p>123 ABC Street, District 1<br>Ho Chi Minh City, Vietnam</p>"),
        ("<h4>Điện Thoại</h4>", "<h4>Phone</h4>"),
        ("<h4>Giờ Làm Việc</h4>", "<h4>Working Hours</h4>"),
        ("<h4>Kết Nối Với Chúng Tôi</h4>", "<h4>Connect with Us</h4>"),
        ("<h3>Bản Đồ</h3>", "<h3>Map</h3>")
    ],
    'frontend/pages/cart.php': [
        ("$message = 'Đã xóa sách khỏi giỏ hàng.';", "$message = 'Book removed from cart.';"),
        ("$message = 'Đã xóa toàn bộ giỏ hàng.';", "$message = 'Cart cleared successfully.';"),
        ("$message = 'Thuê sách thành công! Xem sách đã thuê trong mục Tổng Quan.';",
         "$message = 'Book rented successfully! View your rentals in the dashboard.';"),
        ("<h1 style=\"font-size: 2rem; margin-bottom: 4px;\">Giỏ Hàng Của Bạn</h1>",
         "<h1 style=\"font-size: 2rem; margin-bottom: 4px;\">Your Cart</h1>"),
        ("<p style=\"color: var(--text-muted); margin: 0;\">Xem lại sách bạn muốn thuê</p>",
         "<p style=\"color: var(--text-muted); margin: 0;\">Review the books you want to rent</p>"),
        ("<h3>Giỏ Hàng Trống</h3>", "<h3>Your Cart is Empty</h3>"),
        ("<p>Bắt đầu khám phá bộ sưu tập sách của chúng tôi</p>",
         "<p>Start exploring our book collection</p>"),
        ("<i class=\"fas fa-book\"></i> Khám Phá Sách", "<i class=\"fas fa-book\"></i> Discover Books"),
        ("<span class=\"label\">Giá/ngày</span>", "<span class=\"label\">Price/day</span>"),
        ("<span class=\"label\">Số ngày</span>", "<span class=\"label\">Days</span>"),
        ("<span class=\"label\">Tổng</span>", "<span class=\"label\">Total</span>"),
        ("title=\"Xóa\"", "title=\"Remove\""),
        ("onclick=\"return confirm('Xóa toàn bộ giỏ hàng?')\"", "onclick=\"return confirm('Clear the entire cart?')\""),
        ("placeholder=\"Nhập mã giảm giá (VD: WELCOME10)\"", "placeholder=\"Enter discount code (e.g. WELCOME10)\""),
        ("<i class=\"fas fa-tag\"></i> Áp dụng", "<i class=\"fas fa-tag\"></i> Apply"),
        ("<span>Giảm giá</span>", "<span>Discount</span>"),
        ("<span>Tổng cộng</span>", "<span>Total</span>"),
        ("<i class=\"fas fa-arrow-left\"></i> Tiếp Tục Mua Sắm", "<i class=\"fas fa-arrow-left\"></i> Continue Shopping"),
        ("<i class=\"fas fa-check\"></i> Xác Nhận Thuê", "<i class=\"fas fa-check\"></i> Confirm Rental"),
        ("<span class=\"cart-summary-row\">Tạm tính", "<span class=\"cart-summary-row\">Subtotal"),
        (" cuốn)", " items)"),
        ("<span class=\"cart-summary-row discount-row\">\n                            <span>Giảm giá</span>\n                            <span class=\"cart-discount\">-0đ</span>\n                        </div>",
         "<span class=\"cart-summary-row discount-row\">\n                            <span>Discount</span>\n                            <span class=\"cart-discount\">-0đ</span>\n                        </div>"),
    ],
    'frontend/pages/login.php': [
        ("$error = 'Vui lòng điền đầy đủ thông tin.';", "$error = 'Please fill in all required fields.';"),
        ("$error = 'Tên đăng nhập hoặc mật khẩu không đúng.';", "$error = 'Incorrect username or password.';"),
        ("<h2>Chào Mừng Trở Lại</h2>", "<h2>Welcome Back</h2>"),
        ("<p>Đăng nhập vào tài khoản của bạn</p>", "<p>Log in to your account</p>"),
        ("<label>Tên Đăng Nhập</label>", "<label>Username</label>"),
        ("placeholder=\"Nhập tên đăng nhập\"", "placeholder=\"Enter username\""),
        ("<label>Mật Khẩu</label>", "<label>Password</label>"),
        ("placeholder=\"Nhập mật khẩu\"", "placeholder=\"Enter password\""),
        ("<span class=\"remember-text\">Ghi nhớ đăng nhập</span>", "<span class=\"remember-text\">Remember me</span>"),
        ("<i class=\"fas fa-sign-in-alt\"></i> Đăng Nhập", "<i class=\"fas fa-sign-in-alt\"></i> Login"),
        ("<p>Chưa có tài khoản? <a href=\"register.php\">Đăng Ký Ngay</a></p>",
         "<p>Don't have an account? <a href=\"register.php\">Register now</a></p>")
    ],
    'frontend/pages/register.php': [
        ("$error = 'Vui lòng điền đầy đủ thông tin bắt buộc.';", "$error = 'Please fill in all required fields.';"),
        ("$error = 'Mật khẩu không khớp.';", "$error = 'Passwords do not match.';"),
        ("$error = 'Mật khẩu phải có ít nhất 6 ký tự.';", "$error = 'Password must be at least 6 characters.';"),
        ("$error = 'Tên đăng nhập đã tồn tại.';", "$error = 'Username already exists.';"),
        ("$error = 'Email đã được sử dụng.';", "$error = 'Email is already in use.';"),
        ("$success = 'Đăng ký thành công! Vui lòng đăng nhập.';", "$success = 'Registration successful! Please log in.';"),
        ("<h2>Tạo Tài Khoản</h2>", "<h2>Create an Account</h2>"),
        ("<p>Tham gia BookRent ngay hôm nay</p>", "<p>Join BookRent today</p>"),
        ("<label>Họ và Tên *</label>", "<label>Full Name *</label>"),
        ("placeholder=\"Nguyễn Văn A\"", "placeholder=\"John Doe\""),
        ("<label>Tên Đăng Nhập *</label>", "<label>Username *</label>"),
        ("placeholder=\"nguyenvana\"", "placeholder=\"johndoe\""),
        ("<label>Mật Khẩu *</label>", "<label>Password *</label>"),
        ("placeholder=\"Ít nhất 6 ký tự\"", "placeholder=\"At least 6 characters\""),
        ("<label>Xác Nhận Mật Khẩu *</label>", "<label>Confirm Password *</label>"),
        ("placeholder=\"Nhập lại mật khẩu\"", "placeholder=\"Re-enter password\""),
        ("<i class=\"fas fa-user-plus\"></i> Đăng Ký", "<i class=\"fas fa-user-plus\"></i> Register"),
        ("<p>Đã có tài khoản? <a href=\"login.php\">Đăng Nhập</a></p>",
         "<p>Already have an account? <a href=\"login.php\">Login</a></p>")
    ],
    'frontend/pages/about.php': [
        ("$pageTitle = 'Về Chúng Tôi';", "$pageTitle = 'About Us';"),
        ("<h1 class=\"page-title\">Về MÂY MƠ BOOK</h1>", "<h1 class=\"page-title\">About MÂY MƠ BOOK</h1>"),
        ("<p class=\"page-subtitle\">Câu chuyện của chúng tôi</p>", "<p class=\"page-subtitle\">Our story</p>"),
        ("<h2>Chào mừng đến với MÂY MƠ BOOK</h2>", "<h2>Welcome to MÂY MƠ BOOK</h2>"),
        ("<p>MÂY MƠ BOOK là nền tảng thuê sách trực tuyến hàng đầu Việt Nam, được thành lập với sứ mệnh mang đến cho người yêu sách cơ hội tiếp cận với kho tàng tri thức khổng lồ một cách dễ dàng và tiết kiệm.</p>",
         "<p>MÂY MƠ BOOK is Vietnam's leading online book rental platform, founded to help book lovers access a vast library of titles easily and affordably.</p>"),
        ("<p>Với hơn <strong>15,000+ đầu sách</strong> thuộc nhiều thể loại đa dạng, từ tiểu thuyết, sách kỹ năng, đến các tác phẩm văn học kinh điển, chúng tôi cam kết mang đến trải nghiệm đọc sách tốt nhất cho bạn.</p>",
         "<p>With over <strong>15,000+ titles</strong> across genres like fiction, self-help, and classics, we are committed to delivering the best reading experience.</p>"),
        ("<h3>Tại sao chọn MÂY MƠ BOOK?</h3>", "<h3>Why choose MÂY MƠ BOOK?</h3>"),
        ("<strong>Kho sách đa dạng</strong>", "<strong>Diverse collection</strong>"),
        ("<p>Hơn 15,000 đầu sách thuộc nhiều thể loại khác nhau</p>", "<p>Over 15,000 titles across multiple genres</p>"),
        ("<strong>Chi phí hợp lý</strong>", "<strong>Affordable pricing</strong>"),
        ("<p>Chỉ trả tiền cho những ngày bạn thực sự đọc sách</p>", "<p>Only pay for the days you actually read.</p>"),
        ("<strong>Giao hàng nhanh chóng</strong>", "<strong>Fast delivery</strong>"),
        ("<p>Miễn phí giao hàng cho đơn từ 3 cuốn trở lên</p>", "<p>Free shipping on orders of 3 or more books</p>"),
        ("<strong>Đổi trả dễ dàng</strong>", "<strong>Easy returns</strong>"),
        ("<p>Chính sách đổi trả trong 7 ngày không phí</p>", "<p>7-day no-fee return policy</p>"),
        ("<div class=\"stat-label\">Đầu sách</div>", "<div class=\"stat-label\">Titles</div>"),
        ("<div class=\"stat-label\">Khách hàng</div>", "<div class=\"stat-label\">Customers</div>"),
        ("<div class=\"stat-label\">Đơn hàng</div>", "<div class=\"stat-label\">Orders</div>"),
        ("<div class=\"stat-label\">Đánh giá</div>", "<div class=\"stat-label\">Reviews</div>"),
        ("<h2 class=\"section-title\">Đội Ngũ Của Chúng Tôi</h2>", "<h2 class=\"section-title\">Our Team</h2>"),
        ("<p class=\"section-subtitle\">Những người đam mê sách</p>", "<p class=\"section-subtitle\">Passionate book lovers</p>"),
        ("<p class=\"team-desc\">Đam mê sách từ nhỏ, mong muốn lan tỏa văn hóa đọc đến mọi người.</p>",
         "<p class=\"team-desc\">Passionate about books and dedicated to spreading the reading culture.</p>"),
        ("<p class=\"team-desc\">Đảm bảo mọi đơn hàng được xử lý nhanh chóng và chính xác.</p>",
         "<p class=\"team-desc\">Ensuring every order is handled quickly and accurately.</p>"),
        ("<p class=\"team-desc\">Xây dựng nền tảng công nghệ hiện đại, phục vụ khách hàng tốt nhất.</p>",
         "<p class=\"team-desc\">Building modern technology to serve customers better.</p>")
    ],
    'frontend/pages/book-detail.php': [
        ("$message = 'Thuê sách thành công! Bạn có thể xem trong mục thuê của tôi.';",
         "$message = 'Book rented successfully! You can view it in your rentals.';"),
        ("$message = 'Đã thêm vào giỏ hàng!';", "$message = 'Added to cart!';"),
        ("$message = 'Bạn cần thuê sách này trước khi đánh giá.';",
         "$message = 'You need to rent this book before leaving a review.';"),
        ("$message = 'Vui lòng chọn số sao hợp lệ (1-5).';",
         "$message = 'Please choose a valid star rating (1-5).';"),
        ("$message = 'Vui lòng nhập nội dung bình luận.';",
         "$message = 'Please enter a review comment.';"),
        ("$message = 'Đã gửi đánh giá thành công.';", "$message = 'Review submitted successfully.';"),
        ("$message = 'Không thể gửi đánh giá, vui lòng thử lại.';",
         "$message = 'Unable to submit review. Please try again.';"),
        ("<a href=\"books.php\">Sách</a>", "<a href=\"books.php\">Books</a>"),
        ("<a href=\"books.php?category=<?php echo urlencode((string)($book['category'] ?? '')); ?>\"><?php echo htmlspecialchars((string)($book['category'] ?? 'Sách')); ?></a>",
         "<a href=\"books.php?category=<?php echo urlencode((string)($book['category'] ?? '')); ?>\"><?php echo htmlspecialchars((string)($book['category'] ?? 'Books')); ?></a>"),
        ("<span class=\"book-status available\">Còn Hàng</span>", "<span class=\"book-status available\">In Stock</span>"),
        ("<span class=\"book-status unavailable\">Hết Hàng</span>", "<span class=\"book-status unavailable\">Out of Stock</span>"),
        ("<?php echo htmlspecialchars((string)($book['category'] ?? 'Sách')); ?>", "<?php echo htmlspecialchars((string)($book['category'] ?? 'Books')); ?>"),
        ("Tác giả: <?php echo htmlspecialchars((string)($book['author'] ?? 'Tác giả')); ?>", "Author: <?php echo htmlspecialchars((string)($book['author'] ?? 'Author')); ?>"),
        ("<span class=\"rating-text\"><?php echo $reviewCount > 0 ? number_format($rating, 1) : 'Chưa có'; ?></span>",
         "<span class=\"rating-text\"><?php echo $reviewCount > 0 ? number_format($rating, 1) : 'No reviews yet'; ?></span>"),
        ("<span class=\"review-count\">(<?php echo number_format($reviewCount); ?> đánh giá)</span>",
         "<span class=\"review-count\">(<?php echo number_format($reviewCount); ?> reviews)</span>"),
        ("<?php echo nl2br(htmlspecialchars($book['description'] ?: 'Chưa có mô tả cho cuốn sách này. Thuê ngay để khám phá những gì cuốn sách này mang lại.')); ?>",
         "<?php echo nl2br(htmlspecialchars($book['description'] ?: 'No description available for this book yet. Rent it now to discover what it offers.')); ?>"),
        ("<span class=\"meta-text\">Tác giả</span>", "<span class=\"meta-text\">Author</span>"),
        ("<span class=\"meta-text\">Thời gian thuê</span>", "<span class=\"meta-text\">Rental period</span>"),
        ("Thời Gian Thuê", "Rental Period"),
        ("<option value=\"7\">7 Ngày - <?php echo number_format($book['price_per_day'] * 7, 0); ?>đ</option>",
         "<option value=\"7\">7 days - <?php echo number_format($book['price_per_day'] * 7, 0); ?>đ</option>"),
        ("<option value=\"14\">14 Ngày - <?php echo number_format($book['price_per_day'] * 14, 0); ?>đ</option>",
         "<option value=\"14\">14 days - <?php echo number_format($book['price_per_day'] * 14, 0); ?>đ</option>"),
        ("<option value=\"30\">30 Ngày - <?php echo number_format($book['price_per_day'] * 30, 0); ?>đ</option>",
         "<option value=\"30\">30 days - <?php echo number_format($book['price_per_day'] * 30, 0); ?>đ</option>"),
        ("<strong>Tổng:</strong> (<?php echo number_format($book['price_per_day'], 0); ?>/ngày x <span id=\"daysDisplay\">7</span> ngày)",
         "<strong>Total:</strong> (<?php echo number_format($book['price_per_day'], 0); ?>/day x <span id=\"daysDisplay\">7</span> days)"),
        ("<i class=\"fas fa-book\"></i> Thuê Ngay", "<i class=\"fas fa-book\"></i> Rent Now"),
        ("<i class=\"fas fa-shopping-cart\"></i> Thêm Vào Giỏ Hàng", "<i class=\"fas fa-shopping-cart\"></i> Add to Cart"),
        ("Sách này hiện đang hết hàng. Vui lòng quay lại sau hoặc chọn sách khác.",
         "This book is currently out of stock. Please check back later or choose another title."),
        ("<h2 class=\"section-title\">Đánh Giá & Bình Luận</h2>", "<h2 class=\"section-title\">Reviews & Comments</h2>"),
        ("<p class=\"section-subtitle\">Xem trải nghiệm của người đã thuê sách này</p>",
         "<p class=\"section-subtitle\">See what readers are saying about this book</p>"),
        ("<?php echo $userReview ? 'Cập nhật đánh giá của bạn' : 'Viết đánh giá của bạn'; ?>",
         "<?php echo $userReview ? 'Update your review' : 'Write your review'; ?>"),
        ("<option value=\"1\" <?php echo $selectedRating === 1 ? 'selected' : ''; ?>>1 sao - Kém</option>",
         "<option value=\"1\" <?php echo $selectedRating === 1 ? 'selected' : ''; ?>>1 star - Poor</option>"),
        ("<label for=\"comment\">Bình luận</label>", "<label for=\"comment\">Comment</label>"),
        ("<?php echo $userReview ? 'Cập nhật đánh giá' : 'Gửi đánh giá'; ?>",
         "<?php echo $userReview ? 'Update review' : 'Submit review'; ?>"),
        ("Bạn cần thuê sách này trước khi có thể đánh giá và bình luận.",
         "You need to rent this book before you can leave a review and comment."),
        ("Vui lòng đăng nhập và thuê sách để viết đánh giá.",
         "Please log in and rent the book to leave a review."),
        ("<h3>Chưa có đánh giá</h3>", "<h3>No Reviews Yet</h3>"),
        ("<p>Hãy là người đầu tiên chia sẻ trải nghiệm về cuốn sách này.</p>",
         "<p>Be the first to share your experience with this book.</p>"),
        ("<h2 class=\"section-title\">Sách Liên Quan</h2>", "<h2 class=\"section-title\">Related Books</h2>"),
        ("<p class=\"section-subtitle\">Thêm sách cùng thể loại <?php echo htmlspecialchars($book['category']); ?></p>",
         "<p class=\"section-subtitle\">More books in the <?php echo htmlspecialchars($book['category']); ?> genre</p>"),
        ("<a href=\"books.php?category=<?php echo urlencode($book['category']); ?>\" class=\"btn btn-outline btn-sm\">Xem Thêm <i class=\"fas fa-arrow-right\"></i></a>",
         "<a href=\"books.php?category=<?php echo urlencode($book['category']); ?>\" class=\"btn btn-outline btn-sm\">View More <i class=\"fas fa-arrow-right\"></i></a>")
    ],
    'frontend/pages/books.php': [
        ("$pageTitle = 'Tìm Kiếm: ' . htmlspecialchars($search);", "$pageTitle = 'Search: ' . htmlspecialchars($search);"),
        ("$pageTitle = 'Sách ' . htmlspecialchars($category);", "$pageTitle = 'Books: ' . htmlspecialchars($category);"),
        ("$pageTitle = 'Tất Cả Sách';", "$pageTitle = 'All Books';"),
        ("<p class=\"page-subtitle\"><?php echo count($books); ?> sách được tìm thấy</p>",
         "<p class=\"page-subtitle\"><?php echo count($books); ?> books found</p>"),
        ("placeholder=\"Tìm kiếm theo tên sách, tác giả...\"", "placeholder=\"Search for title or author...\""),
        ("<i class=\"fas fa-search\"></i> Tìm Kiếm", "<i class=\"fas fa-search\"></i> Search"),
        ("<i class=\"fas fa-times\"></i> Xóa", "<i class=\"fas fa-times\"></i> Clear"),
        ("<i class=\"fas fa-check\"></i> Còn hàng", "<i class=\"fas fa-check\"></i> In stock"),
        ("<i class=\"fas fa-times\"></i> Hết hàng", "<i class=\"fas fa-times\"></i> Out of stock"),
        ("title=\"Yêu Thích\"", "title=\"Favorite\""),
        ("<?php echo htmlspecialchars((string)($book['category'] ?? 'Sách')); ?>", "<?php echo htmlspecialchars((string)($book['category'] ?? 'Books')); ?>"),
        ("<i class=\"fas fa-user-edit\"></i> <?php echo htmlspecialchars((string)($book['author'] ?? 'Tác giả')); ?>", "<i class=\"fas fa-user-edit\"></i> <?php echo htmlspecialchars((string)($book['author'] ?? 'Author')); ?>"),
        ("<a href=\"book-detail.php?id=<?php echo $book['id']; ?>\" class=\"btn btn-sm\">Thuê</a>",
         "<a href=\"book-detail.php?id=<?php echo $book['id']; ?>\" class=\"btn btn-sm\">Rent</a>") ,
        ("<h3>Không Tìm Thấy Sách</h3>", "<h3>No Books Found</h3>"),
        ("<p class=\"section-subtitle\">Thử điều chỉnh từ khóa tìm kiếm hoặc bộ lọc.</p>",
         "<p class=\"section-subtitle\">Try adjusting the search terms or filters.</p>"),
        ("<i class=\"fas fa-book\"></i> Xem Tất Cả Sách", "<i class=\"fas fa-book\"></i> View All Books"),
        ("<h2 class=\"section-title\">Khám Phá Thêm</h2>", "<h2 class=\"section-title\">Discover More</h2>"),
        ("<p class=\"section-subtitle\">Tìm sách theo thể loại</p>", "<p class=\"section-subtitle\">Browse books by genre</p>")
    ],
    'frontend/pages/admin/messages.php': [
        ("<span class=\"stat-label\">Chưa đọc</span>", "<span class=\"stat-label\">Unread</span>"),
        ("<span class=\"stat-label\">Đã gửi</span>", "<span class=\"stat-label\">Sent</span>"),
        ("<span>Hộp thư đến</span>", "<span>Inbox</span>"),
        ("<span>Đã gửi</span>", "<span>Sent</span>"),
        ("<span>Đánh dấu tất cả đã đọc</span>", "<span>Mark all as read</span>"),
        ("echo htmlspecialchars($msg['sender_name'] ?? 'Người dùng')", "echo htmlspecialchars($msg['sender_name'] ?? 'User')"),
        ("<span><?php echo htmlspecialchars($msg['subject'] ?: '(Không có tiêu đề)'); ?></span>",
         "<span><?php echo htmlspecialchars($msg['subject'] ?: '(No subject)'); ?></span>"),
        ("<h3>Không có tin nhắn</h3>", "<h3>No messages</h3>"),
        ("<p>Không có tin nhắn nào trong mục này.</p>", "<p>There are no messages in this section.</p>"),
        ("onclick=\"return confirm('Xóa tin nhắn này?')\"", "onclick=\"return confirm('Delete this message?')\""),
        ("<span class=\"sender-name-lg\">Gửi đến: <?php echo htmlspecialchars($viewMessage['receiver_name'] ?? 'Người dùng'); ?></span>",
         "<span class=\"sender-name-lg\">Sent to: <?php echo htmlspecialchars($viewMessage['receiver_name'] ?? 'User'); ?></span>"),
        ("<span class=\"sender-email-lg\">Tin nhắn đã gửi</span>", "<span class=\"sender-email-lg\">Sent message</span>"),
        ("<label><i class=\"fas fa-heading\"></i> Tiêu đề</label>", "<label><i class=\"fas fa-heading\"></i> Subject</label>"),
        ("placeholder=\"Nhập tiêu đề...\"", "placeholder=\"Enter a subject...\""),
        ("<i class=\"fas fa-times\"></i> Hủy", "<i class=\"fas fa-times\"></i> Cancel"),
        ("<i class=\"fas fa-paper-plane\"></i> Gửi", "<i class=\"fas fa-paper-plane\"></i> Send"),
        ("Gửi Thông Báo", "Send Notification"),
        ("<label><i class=\"fas fa-user\"></i> Người dùng</label>", "<label><i class=\"fas fa-user\"></i> User</label>"),
        ("placeholder=\"Tìm theo tên hoặc username...\"", "placeholder=\"Search by name or username...\""),
        ("<option value=\"\">-- Chọn người dùng --</option>", "<option value=\"\">-- Select a user --</option>")
    ],
    'frontend/pages/admin/rentals.php': [
        ("$message = 'Không tìm thấy đơn hàng có mã: ' . htmlspecialchars($searchCode);", 
         "$message = 'No rental found with code: ' . htmlspecialchars($searchCode);"),
        ("<h1 class=\"page-header-title\">Quản lý thuê sách</h1>", "<h1 class=\"page-header-title\">Rental Management</h1>"),
        ("<p class=\"page-header-subtitle\">Duyệt đơn hàng và xác nhận giao trả sách</p>",
         "<p class=\"page-header-subtitle\">Review orders and confirm book pickups and returns</p>"),
        ("<div class=\"stat-card-label\">Đang thuê</div>", "<div class=\"stat-card-label\">Active rentals</div>"),
        ("<div class=\"stat-card-label\">Quá hạn</div>", "<div class=\"stat-card-label\">Overdue</div>"),
        ("<div class=\"stat-card-label\">Đã trả</div>", "<div class=\"stat-card-label\">Returned</div>"),
        ("<h3 class=\"dashboard-card-title\">🔍 Duyệt đơn hàng theo mã</h3>",
         "<h3 class=\"dashboard-card-title\">🔍 Search orders by code</h3>"),
        ("<label style=\"display: block; margin-bottom: 8px; font-weight: 500; color: var(--text-primary);\">Mã đơn hàng</label>",
         "<label style=\"display: block; margin-bottom: 8px; font-weight: 500; color: var(--text-primary);\">Order code</label>"),
        ("<i class=\"fas fa-search\"></i> Tìm kiếm", "<i class=\"fas fa-search\"></i> Search"),
        ("<h3 class=\"dashboard-card-title\">✅ Kết quả tìm kiếm: <?php echo htmlspecialchars($searchCode); ?></h3>",
         "<h3 class=\"dashboard-card-title\">✅ Search results: <?php echo htmlspecialchars($searchCode); ?></h3>"),
        ("<th>Khách hàng</th>", "<th>Customer</th>"),
        ("<th>Sách</th>", "<th>Book</th>"),
        ("<th>Ngày thuê</th>", "<th>Rental Date</th>"),
        ("<th>Trạng thái</th>", "<th>Status</th>"),
        ("<th>Thao tác</th>", "<th>Action</th>"),
        ("<?php echo abs(round($daysLeft)); ?> ngày quá hạn", "<?php echo abs(round($daysLeft)); ?> days overdue"),
        ("<?php echo round($daysLeft); ?> ngày còn lại", "<?php echo round($daysLeft); ?> days remaining"),
        ("'active' => ['label' => 'Đang thuê', 'class' => 'badge-success'],", "'active' => ['label' => 'Active', 'class' => 'badge-success'],"),
        ("'returned' => ['label' => 'Đã trả', 'class' => 'badge-secondary'],", "'returned' => ['label' => 'Returned', 'class' => 'badge-secondary'],"),
        ("'overdue' => ['label' => 'Quá hạn', 'class' => 'badge-danger'],", "'overdue' => ['label' => 'Overdue', 'class' => 'badge-danger'],"),
        ("'cancelled' => ['label' => 'Đã hủy', 'class' => 'badge-secondary']", "'cancelled' => ['label' => 'Cancelled', 'class' => 'badge-secondary']"),
        ("onclick=\"return confirm('Xác nhận khách đã trả sách?')\"", "onclick=\"return confirm('Confirm the book has been returned?')\""),
        ("<i class=\"fas fa-check\"></i> Trả sách", "<i class=\"fas fa-check\"></i> Mark Returned"),
        ("onclick=\"return confirm('Xác nhận khách đã lấy sách?')\"", "onclick=\"return confirm('Confirm the book has been picked up?')\""),
        ("<i class=\"fas fa-handshake\"></i> Đã lấy", "<i class=\"fas fa-handshake\"></i> Picked Up"),
        ("onclick=\"return confirm('Hủy đơn hàng này?')\"", "onclick=\"return confirm('Cancel this order?')\""),
        ("<button type=\"submit\" class=\"btn btn-sm btn-danger\">\n                                <i class=\"fas fa-times\"></i> Hủy đơn\n                            </button>",
         "<button type=\"submit\" class=\"btn btn-sm btn-danger\">\n                                <i class=\"fas fa-times\"></i> Cancel order\n                            </button>")
    ],
    'frontend/pages/admin/settings.php': [
        ("<p class=\"page-header-subtitle\">Quản lý cài đặt hệ thống</p>",
         "<p class=\"page-header-subtitle\">Manage system settings</p>"),
        ("<h4 class=\"settings-section-title\">Thông Tin Cửa Hàng</h4>",
         "<h4 class=\"settings-section-title\">Store Information</h4>"),
        ("<label>Tên Cửa Hàng</label>", "<label>Store Name</label>"),
        ("placeholder=\"Tên cửa hàng\"", "placeholder=\"Store name\""),
        ("<label>Email Liên Hệ</label>", "<label>Contact Email</label>"),
        ("<label>Số Điện Thoại</label>", "<label>Phone Number</label>"),
        ("placeholder=\"Số điện thoại\"", "placeholder=\"Phone number\""),
        ("<label>Địa Chỉ</label>", "<label>Address</label>"),
        ("placeholder=\"Địa chỉ\"", "placeholder=\"Address\""),
        ("<label>Số Ngày Thuê Tối Đa</label>", "<label>Max rental days</label>"),
        ("<small class=\"form-text\">Số ngày tối đa cho một lần thuê sách</small>",
         "<small class=\"form-text\">Maximum number of days per rental</small>"),
        ("<label>Số Sách Thuê Tối Đa</label>", "<label>Max books per rental</label>"),
        ("<small class=\"form-text\">Số sách tối đa một user có thể thuê</small>",
         "<small class=\"form-text\">Maximum number of books a user can rent</small>"),
        ("<label>Phí Trễ Hạn (VNĐ/ngày)</label>", "<label>Late fee (VND/day)</label>"),
        ("<small class=\"form-text\">Phí phạt khi trả sách trễ hạn</small>",
         "<small class=\"form-text\">Penalty fee for late returns</small>"),
        ("<label>Tiền Đặt Cọc (VNĐ)</label>", "<label>Deposit (VND)</label>"),
        ("<small class=\"form-text\">Tiền đặt cọc khi thuê sách</small>",
         "<small class=\"form-text\">Deposit required for rentals</small>"),
        ("<label>Phí Ship Miễn Phí (VNĐ)</label>", "<label>Free shipping threshold (VND)</label>"),
        ("<small class=\"form-text\">Miễn phí ship cho đơn từ giá trị này</small>",
         "<small class=\"form-text\">Free shipping for orders above this amount</small>"),
        ("<label>Phí Ship Mặc Định (VNĐ)</label>", "<label>Default shipping fee (VND)</label>"),
        ("<small class=\"form-text\">Phí ship cho đơn dưới giá trị miễn phí</small>",
         "<small class=\"form-text\">Shipping fee for orders below the free threshold</small>"),
        ("<i class=\"fas fa-user-cog\"></i> Tài Khoản Admin", "<i class=\"fas fa-user-cog\"></i> Admin Account"),
        ("<label>Tên Đăng Nhập</label>", "<label>Username</label>"),
        ("<label>Họ Tên</label>", "<label>Full Name</label>"),
        ("<label>Đổi Mật Khẩu</label>", "<label>Change Password</label>"),
        ("<label>Xác Nhận Mật Khẩu</label>", "<label>Confirm Password</label>"),
        ("placeholder=\"Xác nhận mật khẩu\"", "placeholder=\"Confirm password\""),
        ("<i class=\"fas fa-key\"></i> Cập Nhật Tài Khoản", "<i class=\"fas fa-key\"></i> Update Account"),
    ],
    'frontend/pages/admin/index.php': [
        ("return context.parsed.y.toLocaleString('vi-VN') + 'đ';", "return context.parsed.y.toLocaleString('en-US') + 'đ';")
    ]
}

for path, reps in replacements.items():
    p = Path(path)
    if not p.exists():
        print(f'FILE MISSING: {path}')
        continue
    text = p.read_text(encoding='utf-8')
    for old, new in reps:
        if old not in text:
            print(f'MISSING: {path}: {old}')
        text = text.replace(old, new)
    p.write_text(text, encoding='utf-8')
print('translation patch applied')
